spring:
  application:
    name: this

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/whythis}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  configuration:
    cacheEnabled: true   # ?? ???, ??? ????
    lazy-initialization: false   # Mapper ? ??? ??, true ??? ? ???? ??? ??? ? ??? ???? ???? ??? ??? ??? ? ??.
    type-aliases-package: com.why.that.dao